language: python

python:
  - 2.7

env:
  - DJANGO=1.4.22 TASTYPIE=0.9.16
  - DJANGO=1.6.11 TASTYPIE=0.12.1
  - DJANGO=1.9.7 TASTYPIE=0.13.3

matrix:
  include:
    - python: 3.5
      env: DJANGO=1.9.7 TASTYPIE=0.13.3

install:
  - pip install coveralls sorl-thumbnail pyyaml pillow
  - pip install -q django==$DJANGO django-tastypie==$TASTYPIE
  - pip install --upgrade mock

script:
  - coverage run setup.py test

after_success:
  - coveralls