language: python

matrix:
  include:
    - env: DJANGO=1.4.22 TASTYPIE=0.9.16
    - env: DJANGO=1.6.11 TASTYPIE=0.12.1
    - env: DJANGO=1.9.2 TASTYPIE=0.13.3
    - python: 3.5
      env: DJANGO=1.9.2 TASTYPIE=0.13.3

install:
  - pip install coveralls sorl-thumbnail pyyaml pillow
  - pip install -q django==$DJANGO django-tastypie==$TASTYPIE
  - pip install --upgrade mock

script:
  - coverage run ./manage.py test tastypie_sorl_thumbnail

after_success:
  - coveralls